### ISSUE TITLE
REDbot double URL encoding tildes (~)

### ISSUE THREAD

**Issue by matt-lvi** [mnot/redbot#130]
I have some assets with tildes (~) in the file names.  When I check them in REDbot, it url encodes them to "%7E".  This is an issue for the content-negotiation checks because the percent sign is subsequently URL encoded again to "%25" and it says that the asset is returning a 404.

So, for the url /style~23715.css, the first check shows this in the access log:

    50.56.234.188 - - [08/Oct/2013:20:56:19 +0200] "GET /style%7E23715.css HTTP/1.1" 200 60045 "-" "RED/1 (http://redbot.org/)"

This works, but the following request shows this:

    50.56.234.188 - - [08/Oct/2013:20:56:19 +0200] "GET /style%257E23715.css HTTP/1.1" 404 398 "-" "RED/1 (http://redbot.org/)"

This second one is a 404.  As far as I can tell, there is no reason not to use tildes in file names.

**Comment by mnot** [comment]
Think this particular issue was fixed, although Python URL parsing is still... suboptimal. If you see it again, please reopen (and thanks for the bug).
