### ISSUE TITLE
Display a reference to Apache bug when flagging identical Etags?

### ISSUE THREAD

**Issue by bortzmeyer** [mnot/redbot#135]
My site http://www.bortzmeyer.org/ raises the error "The ETag doesn't change between negotiated representations." The HTTP server is a standard, unmodified Apache. I believe that the error is related to this Apache bug: https://issues.apache.org/bugzilla/show_bug.cgi?id=46538 opened a long time ago but not yet concluded.

Since Apache is very common, and that apparently anyone who activates compression will get this error, why not add a reference in the error text going to the Apache bug page?

**Comment by mnot** [comment]
There's a reference to the apache bug (not the tomcat bug) in the detail text now.
