### ISSUE TITLE
Test for range and partial content wrong?

### ISSUE THREAD

**Issue by bortzmeyer** [mnot/redbot#137]
On my site http://www.bortzmeyer.org/, redbot says "A ranged request returned the full rather than partial content." I'm puzzled since it is a standard unmodified Apache, which handles Range requests for static content (the only content on this site). When I test it manually, with curl, it seems to work:

```
% curl  -v --range "20001-" http://www.bortzmeyer.org/images/moi.jpg > moi-partial.jpg
...
> GET /images/moi.jpg HTTP/1.1
> Range: bytes=20001-
...
< HTTP/1.1 206 Partial Content
...
< Accept-Ranges: bytes
< Content-Length: 34906
< Content-Range: bytes 20001-54906/54907
...
100 34906  100 34906    0     0  70285      0 --:--:-- --:--:-- --:--:-- 93331
```

There is a 206 and a Content-Range. If I ask for less data:

```
% curl  -v --range "40001-" http://www.bortzmeyer.org/images/moi.jpg > moi-partial.jpg 
...
> GET /images/moi.jpg HTTP/1.1
> Range: bytes=40001-
...
< HTTP/1.1 206 Partial Content
< Accept-Ranges: bytes
< Content-Length: 14906
< Link: <http://www.gnu.org/copyleft/fdl.html>; rel="license"; title="GFDL"
< Content-Range: bytes 40001-54906/54907
...
{ [data not shown]
100 14906  100 14906    0     0  46203      0 --:--:-- --:--:-- --:--:-- 53812
```

There is indeed less data transfered (see the Content-Length:, the Content-Range; the amount of bytes transfered by curl and also - not shown here - 'ls -l' on the resulting file).

It might be a bug, may I suggest that redbot displays the full conversation, with HTTP headers, in order to investigate?

**Comment by mnot** [comment]
Hey,

Sorry for the delay; redbot wasn't getting much attention for a while. 

Could you see if this is still a problem? You can now see the partial content response (etc.) linked from the result page.

**Comment by bortzmeyer** [comment]
Still a problem for me:

Partial Content (Partial Content response )
A ranged request returned the full rather than partial content.

**Comment by mnot** [comment]
OK, try now.

**Comment by bortzmeyer** [comment]
Works fine, now: "Partial Content (Partial Content response )

    A ranged request returned the correct partial content."

**Comment by mnot** [comment]
Thanks for the report!
