### ISSUE TITLE
protocol less url handled wrong

### ISSUE THREAD

**Issue by skojin** [mnot/redbot#143]
for https://redbot.org/?descend=True&uri=http://www.mysite.com/

if mysite have resources starts with //someurl.com/script.js it handled wrong, just like relative link

https://redbot.org/?uri=http://www.mysite.com/%E2%80%9C//www.googletagmanager.com/ns.html?id%3DGTM-WXS8GQ%E2%80%9D

**Comment by mnot** [comment]
Sorry for the delay. This works for me now; if ti's still an issue, please reopen.
