### ISSUE TITLE
New htaccess

### ISSUE THREAD

**Issue by claudiomiguelmuller** [mnot/redbot#147]
I try redbot.org to verify my htaccess.

One of the recomendations is disable "pragma: no-cache".

I modify my htaccess with "header unset pragma".

I try again rebot.org to verify my htaccess but the recomendations display again about pragma.

How much time i need to wait to try again to verify with rebot my htaccess?

Obs: Sorry my english! I am from Brazil.

**Comment by mnot** [comment]
Hi,

REDbot checks every time you reload, so it's an issue with your server.

Cheers,
