### ISSUE TITLE
Redbot.org down

### ISSUE THREAD

**Issue by ElijahLynn** [mnot/redbot#158]
Can anyone else access redbot.org? I get a hung response.

**Comment by ElijahLynn** [comment]
Hrm, http://downforeveryoneorjustme.com/http://redbot.org says it is just me. Investigating.

**Comment by ElijahLynn** [comment]
Hrm, was just really slow I guess. Asked a coworker and it sluggishly came up and then I was able to load it after that too. Was not loading for at least 10-20 seconds though and I would just keep trying again. Not actually letting it fully timeout. So... that's that.

**Comment by mnot** [comment]
Sorry about that, I'm testing the experimental mod_http2 in Apache, and it occasionally brings the server down. I'll bounce it, that should clear things up.

**Comment by ElijahLynn** [comment]
Ahh fun, thanks for the explanation!
