### ISSUE TITLE
Robots.txt parsed incorrectly

### ISSUE THREAD

**Issue by rugk** [mnot/redbot#161]
I tried to allow RED when I also use `*` to disallow all other robots, but the robots.txt is not checked correctly.
I even already placed `User-agent: *` (disallow) at the end, but it REDbot still got it wrong.

## These robots.txt allow REDbot

Example 1:
```robots
User-agend: RED
Allow: /

User-agent: *
Disallow: /
```

Example 2:
```robots
User-agend: RED
Disallow:

User-agent: *
Disallow: /
```

Example 3 (webadmins should not do it in this way for legacy robots, but theoretically it should be okay):
```robots
User-agent: *
Disallow: /

User-agend: RED
Disallow:
```

**Comment by mnot** [comment]
Are you using `User-agend` or `User-agent`?

REDbot uses Python's robot parser - https://docs.python.org/2/library/robotparser.html

**Comment by rugk** [comment]
Oh, ehm... 

Upps.
I used `User-agend` in my tests, so indeed it works now. Sorry.
