### ISSUE TITLE
Weird CGI output pause

### ISSUE THREAD

**Issue by mnot** [mnot/redbot#164]
For some sites, writing to STDOUT seems to pause on CGI.

E.g., http://medexpert-help.ru

I can mitigate this by moving to line-buffering (from unbuffered), but the page still doesn't complete.

**Comment by mnot** [comment]
Another: http://www.but.fr

**Comment by mnot** [comment]
Offending write is in `html.py:SingleHtmlFormatter.finish_output()` on the `self.state.response.complete` path. 

I've checked; all of the template args are completing successfully, and character encoding is working fine; it's in the `sys.stdout.write`.

**Comment by googleanalyticsresoneo** [comment]
Another one is https://www.auchan.fr/assets/v15aaa57d2c780/tagCommander/tc_auchanfr_2_v52.js for example

**Comment by mnot** [comment]
It appears that if I write more than 81919 octets to STDOUT from a CGI script at a time, Apache gets unhappy. Writing a minimal test case now.

![](http://memedad.com/create/thumbnails/34.jpg)

**Comment by mnot** [comment]
Simplest repro has a slightly different threshold (on my box):

~~~ python
#!/usr/bin/env python2

import sys
print "Status: 200 OK"
print "Content-Type: text/html"
print
sys.stdout.write("a"*77784)
~~~

If I reduce to `77783`, it doesn't block.

If I turn of HTTP/2 (e.g., in Firefox, restarting after changing prefs), it doesn't block.

Will commit a workaround shortly. @icing any comment? Believe I'm running 1.5.11.

**Comment by icing** [comment]
Try [v1.6.2](https://github.com/icing/mod_h2/releases/tag/v1.6.2) please, @mnot.
![oops](https://pbs.twimg.com/media/Csq7Hl2XYAAlFJ6.jpg:small)

**Comment by mnot** [comment]
@icing LGTM, thanks. I'm going to leave the workaround in for now.
