### ISSUE TITLE
error: can't copy 'redbot/assets/logo

### ISSUE THREAD

**Issue by meulie** [mnot/redbot#185]
Hi,

I'm getting a `error: can't copy 'redbot/assets/logo': doesn't exist or not a regular file`. Something missing in commit 0ddb80589c97ee3564102839436dd18e2a237e8c ?

**Comment by mnot** [comment]
When does this happen?

**Comment by meulie** [comment]
I do:
`git clone https://github.com/mnot/redbot.git`
`cd redbot`
`python3 setup.py install`

the output of the last command ends with: 
 `creating build/lib/redbot/assets`
`copying redbot/assets/style.css -> build/lib/redbot/assets`
`copying redbot/assets/red_style.css.map -> build/lib/redbot/assets`
`copying redbot/assets/red_style.css -> build/lib/redbot/assets`
`error: can't copy 'redbot/assets/logo': doesn't exist or not a regular file`

**Comment by mnot** [comment]
Sorry for the wait; thanks for the report.
