### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE on aztpensii.ro

### ISSUE THREAD

**Issue by dan2468** [mnot/redbot#188]
Fetching `https://aztpensii.ro:8888/employer/pck_web_new.p_login` works in the browser and with curl, but RedBot returns `Connection error ([SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:749))`

**Comment by mnot** [comment]
Hi,

I can't reproduce this; did you change something in the meantime?

**Comment by dan2468** [comment]
I guess they changed something server-side.
Close this for now, thanks.
