### ISSUE TITLE
Type annotation glitches

### ISSUE THREAD

**Issue by mnot** [mnot/redbot#189]
CI is failing because of https://github.com/PyCQA/pylint/issues/1295. Hopefully there will be a new release soon.

Currently requires 3.5.3 or greater because of http://stackoverflow.com/questions/42942867/typing-optional-as-a-return-value-in-3-5-2.

**Comment by h1z1** [comment]
Why on earth does python continue to do silly things ..   Has there been any update to this or can redbot be patched?   Forcing people to upgrade to 3.5.2 or higher seems equally silly, it's fairly recent.  It's certainly not available in CentOS 6 or 7.

**Comment by mnot** [comment]
This is getting annoying; it's fixed in Python, but Travis still doesn't have 3.6.3.

**Comment by mnot** [comment]
It now works with 3.6.2, which seems to be more broadly available now.
