### ISSUE TITLE
Is Redbot.org down? 

### ISSUE THREAD

**Issue by mitchellkrogza** [mnot/redbot#191]
Been trying to open Redbot for the past 2 hours and I just will not load the page. Anything up?

**Comment by szepeviktor** [comment]
Google webcache seen it last time at `2017. ápr. 9. 08:18:57 GMT.`

**Comment by mnot** [comment]
Sorry about that, should be back up now. I've been having trouble over the last few weeks; I suspect it was the version of @icing's mod_h2 packaged in arch. Just upgraded to HEAD, hopefully, that will help. Please ping me here or on twitter (same username) if it happens again. Thanks!

**Comment by mitchellkrogza** [comment]
👍  Thanks @mnot it's up again. Thanks for such a great tool. I want to look into running my own redbot on one of my servers soon, busy shuffling things around and will soon have a dedicated server for it. Keep up the good work 😉
