### ISSUE TITLE
Spurious content negotiation failure

### ISSUE THREAD

**Issue by r-love** [mnot/redbot#193]
I am seeing a spurious content negotiation error for my website, rlove.org:

[Redbot example](https://redbot.org/?id=1g2_ko2z&req_hdr=User-Agent%3ARED/1%20(https://redbot.org/)&req_hdr=Referer%3Ahttps://rlove.org/&check_name=Content%20Negotiation)

It says "The compressed response was compressed using GZip, but the data was corrupt."

I'm not able to reproduce this on my end:

- `gzip --test` on the payload (I use static compression) succeeds
- `curl --compressed https://rlove.org/` is identical to `curl https://rlove.org/`
- Page loads fine in Chrome and Firefox

I've tried a bunch of other ways to check if I am serving corrupt corrupted content, and I cannot verify. Therefore I think this test has a bug.

**Comment by mnot** [comment]
What's being used to compress the response?

**Comment by r-love** [comment]
`gzip --best --stdout source > target`

And then `gzip_static` in nginx to serve.

This does not return error:

`curl --silent -H "Accept-Encoding: gzip" https://rlove.org/ | gzip --test`

But Redbot does.

I'm happy to debug further if you have ideas; I don't know when this started, but I know it didn't use to happen.

**Comment by r-love** [comment]
Here's the full text of the error from Redbot:

> The compressed response was compressed using GZip, but the data was corrupt.

And the details from the tooltip:

> GZip-compressed responses use zlib compression to reduce the number of bytes transferred on the wire. However, this response could not be decompressed; the error encountered was "Error -3 while decompressing data: invalid stored block lengths".
>
> 1,798 bytes were decompressed successfully before this; the erroneous chunk starts with (in hex):
>
> (cQ\xf9\xd2\xc6\x136\x83e\xb1Y\xbfk\xeb-\x9

You can generate this yourself with a Redbot run against `https://rlove.org/` and then click "Content Negotiation response."

**Comment by mnot** [comment]
Sorry for the delay, this should be fixed now. Please reopen if not.

**Comment by r-love** [comment]
Confirm fixed. Thank you.
