### ISSUE TITLE
Unexpected "The response body is different when content negotiation happens."

### ISSUE THREAD

**Issue by nigelbpeck** [mnot/redbot#195]
Thanks for this awesome tool. I am getting in the report that:

 > The response body is different when content negotiation happens. 

The only content negotiation that occurs is based on "Accept-Encoding" and the only two variations are gzipped or not. The gzipping itself is done by Varnish, which is serving both copies, and there is only one origin server. The cache only stores the gzipped version and any requests for the plain version are unzipped on the fly. So there is no reason why the body would be different in those cases. The site being tested is:
https://www.sharphosting.uk/

Sorry if this is something I'm missing, but all seems to be in order so this seems to be an issue of some kind with the software. I couldn't get more detailed information from the software to see exactly what's causing this warning.

**Comment by r-love** [comment]
I'm not a developer, just a user, but this does indeed look like a bug in redbot:

```
$ curl -H 'accept-encoding: gzip' https://www.sharphosting.uk/ | gzip -d | md5sum
$ curl https://www.sharphosting.uk/ | md5sum
```

Both give the same value.

**Comment by consultingroup** [comment]
@mnot

Same problem here: https://redbot.org/?uri=https%3A%2F%2Fwww.consultingroupitaly.com%2Fsitemap_index.xml

Any solution?

**Comment by mnot** [comment]
Deploying now; thanks for the report and sorry for the delay. Please reopen (or open a new issue) if this persists (giving it a couple of more minutes to get out).

**Comment by consultingroup** [comment]
It works now, thanks.
