### ISSUE TITLE
Will it be possible to feed RedBot a GET request and response headers to analyze?

### ISSUE THREAD

**Issue by elico** [mnot/redbot#202]
Hey,

I published a tool which dumps an ICAP RESPMOD request of a GET request with the headers of the request and the response(no body).
I was wondering if there an option to take one of these requests dump files and to let RedBot analyze them.
Or maybe add a feature for it?

an example dump file is:
```
ESPMOD icap://127.0.0.1:1344/dumper ICAP/1.0
date: Wed, 11 Apr 2018 16:52:13 GMT
encapsulated: req-hdr=0, res-hdr=105, res-body=413
preview: 0
allow: 204
host: 127.0.0.1:1344

GET http://ngtech.co.il/index.html HTTP/1.1
Accept: */*
User-Agent: curl/7.29.0

HTTP/1.1 200 OK
Content-Length: 17230
Accept-Ranges: bytes
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Origin: *
Content-Type: text/html
Date: Wed, 11 Apr 2018 16:52:13 GMT
Last-Modified: Tue, 03 Apr 2018 20:19:05 GMT
Server: nginx/1.10.3 (Ubuntu)
Vary: Accept-Encoding
``` 
I can cleanup all relevant details\headers\text and push the relevant data.

**Comment by mnot** [comment]
ICAP no, but see #80. I could see taking a textual form of some kind too.

**Comment by elico** [comment]
@mnot HAR is good enough.
I can easily convert the dumped response to HAR or any similar format.
