### ISSUE TITLE
Missing space after header

### ISSUE THREAD

**Issue by szepeviktor** [mnot/redbot#207]
https://redbot.org/?uri=https%3A%2F%2Fwww.example.com%2Fpuppies

The space is actually received over HTTP but not displayed.

```
    Content-Type:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```

![kep](https://user-images.githubusercontent.com/952007/43155442-b69471fc-8f77-11e8-973d-f78b947cf9ee.png)

Please advise.

**Comment by mnot** [comment]
Hi,

Thanks for the report. I'm not seeing that on the live resource., and that's not a well-formed content-type header. Do you have a live example?

Cheers,

**Comment by szepeviktor** [comment]
Thank you for your answer.

I think IANA fixed example.com!
