### ISSUE TITLE
Check HTTP/1.0

### ISSUE THREAD

**Issue by mnot** [mnot/redbot#21]
Some servers behave differently using HTTP/1.0, either because chunked encoding is not used (length delimitation), or because they think that they need to send back different headers (e.g., Cache-Control).

RED should send a 1.0 request and see if there's any appreciable difference.

**Comment by mnot** [comment]
Nah.

**Comment by spaceone** [comment]
Hm, what does Nah mean? I think this feature would be good to test servers HTTP/1.0 compliance.
