### ISSUE TITLE
VARY_INCONSISTENT Empty Vary headers has backticks

### ISSUE THREAD

**Issue by szepeviktor** [mnot/redbot#217]
https://github.com/mnot/redbot/blob/853fc42a94c2f5a7a41392a6a9b4b0213f09724b/redbot/resource/active_check/conneg.py#L185

![kep](https://user-images.githubusercontent.com/952007/52543659-942ac800-2dab-11e9-86cc-8956a5c86b00.png)

**Comment by mnot** [comment]
Yes. This is an annoying quirk of Markdown; I'll have to figure out a systemic way to handle empty content in these cases. Thanks for the report.

**Comment by szepeviktor** [comment]
Thank you for fixing it.
