### ISSUE TITLE
The PHPSESSID Set-Cookie header has an unknown attribute, 'SameSite'.

### ISSUE THREAD

**Issue by Somebody62** [mnot/redbot#219]
The SameSite attribute of a cookie has been added to the newest versions of Edge, Firefox, Chrome, and Safari, according to [this site](https://caniuse.com/#search=samesite). However, REDbot thinks that 'This Set-Cookie header has an extra parameter, "SameSite".', and that 'Browsers will ignore it.'.

**Comment by mnot** [comment]
Now #225.
