### ISSUE TITLE
More Details About Connection Error Needed

### ISSUE THREAD

**Issue by halilozanyilmaz** [mnot/redbot#228]
Hello,
Recently I had google crawl issues on my website (some files were not being loaded correctly), and I was discussing this issue on google support forum. 

One guy sent me the below link and said that I may be blocking google bot.

> https://redbot.org/?uri=https%3A%2F%2Ftest.tisort.ist&req_hdr=User-Agent%3Agooglebot

After this I had long conversations with my hosting team (siteground). Three Senior Support Person checked the issue, and 1 server side person checked issue, and they all said that there is nothing blocking the googlebot, and there is no clues about this issue on server side. They said maybe I can get more information from you.

So what kind of information can I provide to them ? Redbot is just telling me connection error. This detail is not helping me. Can you give some detail, so I can tell my hosting team on your behalf. I need to provide them some details.

Thank you.

**Comment by mnot** [comment]
This is a TCP connection error; it's not a HTTP issue, it's that the client can't contact your server at all. It might be because the server isn't listening, or because there's a firewall blocking it in between.

Can you contact your server from the open internet (e.g., from a home connection)?

**Comment by halilozanyilmaz** [comment]
No problem with home connection: Here is the link, you can see yourself:

> https://test.tisort.ist/

It works when header User-Agent is not added as below

https://redbot.org/?uri=https%3A%2F%2Ftest.tisort.ist

I asked siteground about firewall and they say they are not blocking. They said like this:

> I can confirm that most of the third-party tools such as redbot.org are blocked by our security systems because the requests they send attempt to impersonate another service - very often a malicious practice

But when I check siteground.com url with user-agent:googlbot, it can contact the server. So I am not sure this is valid in this case.
