### ISSUE TITLE
"X-Pad" header should be safe to omit

### ISSUE THREAD

**Issue by 1jj** [mnot/redbot#229]
There is a (not that small) domain provider sending `X-Pad: avoid browser bug` for all frame redirects.
Tooltip shows this:

> The X-Pad header is used to "pad" the response header size.
> Very old versions of the Netscape browser had a bug whereby a response whose headers were exactly 256 or 257 bytes long, the browser would consider the response (e.g., an image) invalid.
> Since the affected browsers (specifically, Netscape 2.x, 3.x and 4.0 up to beta 2) are no longer widely used, it's probably safe to omit this header.

It should say that this header is absolute safe to omit,
as browsers are fixed for 22 years now.

**Comment by mnot** [comment]
Makes sense.
