### ISSUE TITLE
Redbot is not working on http server

### ISSUE THREAD

**Issue by truelet** [mnot/redbot#237]
I have installed redbot and all it's required applicaitons like python, thor etc.
I am able to run redbot with service. and it is running as service on my server.
How can I run it on my http server?
I have repo cloned in my root folder of apache /var/www/html/redbot

**Comment by mnot** [comment]
Hi,

You need support for how to configure your Web server; this isn't a redbot issue.

Thanks,

**Comment by truelet** [comment]
Hi,
Can you please provide any references to setup redbot on http server with
apache
My redbot is working as service. But not running on web server.
Do i need to clone the repo or need to do settings for service. I have to
setup the redbot on my server and I received all solutions on net but
didn't get it worked.

System details:
Centos7
Python3.6
Apache >2.0
Redbot installed through sh command.

Thanks
