### ISSUE TITLE
redbot.org/?uri=<uri> responds with 502 Proxy Error

### ISSUE THREAD

**Issue by Malvoz** [mnot/redbot#240]
FYI @mnot

![image](https://user-images.githubusercontent.com/26493779/67990503-684fbb00-fc36-11e9-927a-1b61dbbd1101.png)

**Comment by mnot** [comment]
Thanks for the report, I've kicked it, and am hunting down the root cause.

**Comment by Malvoz** [comment]
@mnot This happened again just now.
