### ISSUE TITLE
[question] Classification of HTTP headers

### ISSUE THREAD

**Issue by szepeviktor** [mnot/redbot#261]
I'm starting to repair HTTP headers of files in an AWS S3 bucket.

How would one categorize headers?
All I can come up with

1. request related (like Vary and Allow)
1. file type
1. authentication
1. caching
1. SSL
1. security

**Comment by mnot** [comment]
It's a good question, but not an issue here.

**Comment by szepeviktor** [comment]
for googler: https://www.geeksforgeeks.org/http-headers/
