### ISSUE TITLE
Document how to generate js & the css assets

### ISSUE THREAD

**Issue by kinow** [mnot/redbot#271]
Hi!

I'm looking at some of the assets and trying to modify a few things to run it locally, but I couldn't find a way to re-generate the sourcemap or update the generated js file.

If someone could tell me where to look, I can give it another try and prepare a pull request updating CONTRIBUTING.md or another file.

Thanks!
Bruno

**Comment by mnot** [comment]
It's `make redbot/assets`.

A PR would be great.

**Comment by kinow** [comment]
Made good progress, installed `cssmin`, `sassc`, and other tools with either `npm install --global` or `apt`. But now I got stuck on an error and have no idea how to solve.

Any tips @mnot ?

```
kinow@ranma:~/Development/python/workspace/redbot$ make redbot/assets
webpack-cli src/js/red_script.js src/js/red_request.js src/js/red_response.js src/js/red_response_multi.js --config src/js/webpack.config.js --mode production --output redbot/assets/script.js
Hash: 7a931383a83701447266
Version: webpack 4.43.0
Time: 223ms
Built at: 05/12/2020 8:34:32 PM
 2 assets
Entrypoint main = script.js script.js.map
[0] ./src/js/red_util.js 1.05 KiB {0} [built]
[1] multi ./src/js/red_script.js ./src/js/red_request.js ./src/js/red_response.js ./src/js/red_response_multi.js 64 bytes {0} [built]
[2] ./src/js/red_script.js 1.79 KiB {0} [built]
[3] ./src/js/red_request.js 5.06 KiB {0} [built]
[4] ./src/js/red_response.js 3.3 KiB {0} [built]
[5] ./src/js/red_response_multi.js 1.47 KiB {0} [built]

ERROR in ./src/js/red_response_multi.js
Module not found: Error: Can't resolve 'tippy.js' in '/home/kinow/Development/python/workspace/redbot/src/js'
 @ ./src/js/red_response_multi.js 3:0-28 11:4-9 28:4-9
 @ multi ./src/js/red_script.js ./src/js/red_request.js ./src/js/red_response.js ./src/js/red_response_multi.js

ERROR in ./src/js/red_response.js
Module not found: Error: Can't resolve 'tippy.js' in '/home/kinow/Development/python/workspace/redbot/src/js'
 @ ./src/js/red_response.js 4:0-28 16:4-9 62:4-9
 @ multi ./src/js/red_script.js ./src/js/red_request.js ./src/js/red_response.js ./src/js/red_response_multi.js
Makefile:113: recipe for target 'redbot/assets/script.js' failed
make: *** [redbot/assets/script.js] Error 2

```

**Comment by kinow** [comment]
I checked and `tippy.js` is present on `node_modules`, and the `index.d.js` is exporting the `tippy` module. Could it be missing a loader, plugin, or configuration in webpack?

**Comment by mnot** [comment]
Ah, I see what it is -- it was unintentionally excluded from the repo by `.gitignore`. 

Should be fixed, and I changed things to use a Python virtualenv + npx, so you should just need Python and NodeJS. See `CONTRIBUTING.md`, and happy to fix any issues you encounter / lingering confusion (this has been pretty much a sole developer project for a while).

I'm also thinking about using the same approach to get `src/node_modules` out of the repo.

Thanks!

**Comment by kinow** [comment]
Brilliant! Thanks a lot @mnot !
