### ISSUE TITLE
Unable to test with Docker

### ISSUE THREAD

**Issue by kinow** [mnot/redbot#276]
With the two pending PR's, I'm able to run REDbot locally :tada: 

However, I am not able to connect to any site. Tried https://kinoshita.eti.br, https://usp.br, https://globo.com. Every site failed with the same message. Tried changing settings in `extra/config-docker` (confirmed in `ps -a` that the process is running with that file) and then rebuilding the image, but it still refused to work.

What am I missing?

Thanks!
Bruno

**Comment by kinow** [comment]
![image](https://user-images.githubusercontent.com/304786/81889878-b89dd180-95f8-11ea-9b60-4ef07d97e235.png)

The error and the JS console messages.

By the way, `make redbot/assets` is working fine now. Thanks for fixing that! CONTRIBUTING.md looks good.

**Comment by mnot** [comment]
I'm getting that too; not sure what's going on (I usually don't use docker for this project, it was a contrib from someone else). Will have a look.

**Comment by kinow** [comment]
Sure, thanks! I had a look at the thor documentation, to see if I could understand what's going on, but still no idea. I enabled the setting to save the... response I think? In `/tmp`, and it created some binary files, but I didn't know how to inspect them.

Also checked and I am able to ping google.com, globo.com, etc, from within the container :confused:

**Comment by mnot** [comment]
From testing in the container, it seems like it's HTTPS-specific.

**Comment by mnot** [comment]
Try now; the latest release of thor should fix this.

**Comment by kinow** [comment]
Working now! 

![image](https://user-images.githubusercontent.com/304786/82661833-df0adf00-9c80-11ea-99f9-9b06fbee83c1.png)

Thanks @mnot !!!
