### ISSUE TITLE
`Date` header for Varnish-cached resource

### ISSUE THREAD

**Issue by dontcallmedom** [mnot/redbot#284]
While checking the W3C home page with redbot, I noticed it flagged the server's clock being behind for a number of embedded resources, e.g.
  https://redbot.org/?uri=https%3A%2F%2Fwww.w3.org%2F2008%2Fsite%2Fimages%2Fheader-link&req_hdr=User-Agent%3ARED%2F1.5%20(https%3A%2F%2Fredbot.org%2F)&req_hdr=Referer%3Ahttps%3A%2F%2Fwww.w3.org%2F&check_name=default

The resources that got flagged are apparently those served through a Varnish cache.

It emerged that Varnish considers this a feature:
https://github.com/varnishcache/varnish-cache/commit/89870e0bbd785964c322e1e453f492d747731c88 (if I read that right)

It may very well bug a Varnish bug rather than an issue for redbot, but I thought I would start here in case I misinterpret the redbot report or the intent behind Varnish.

**Comment by mnot** [comment]
You have it correct; it's a Varnish bug.

There are some details talking about this if you hover over the note about the date being off -- but they were hidden by a bug that I just fixed. Take a look :)

**Comment by dontcallmedom** [comment]
thanks! the hover pop-up links to http://www2.research.att.com/~edith/Papers/HTML/usits01/index.html which is 404 FYI - https://www.usenix.org/legacy/events/usits01/full_papers/cohen/cohen_html/index.html seems to be an alternative URL that works (if my research in archive.org is correct)

**Comment by mnot** [comment]
Fixed - thx!
