### ISSUE TITLE
Redbot's hoster does not speak TLS 1.2

### ISSUE THREAD

**Issue by szepeviktor** [mnot/redbot#287]
So in my strict Firefox I get: `SSL_ERROR_PROTOCOL_VERSION_ALERT`
@mnot Please help!

**Comment by mnot** [comment]
Update your firefox. And please don't open multiple issues for the same underlying problem.

**Comment by szepeviktor** [comment]
Hello Mark!
I see. My Firefox is not supporting TLS 1.3
