### ISSUE TITLE
Redbot does not pass its own test :(

### ISSUE THREAD

**Issue by szepeviktor** [mnot/redbot#288]
Please see https://redbot.org/?uri=https%3A%2F%2Fredbot.org%2F

**Comment by mnot** [comment]
Works for me.

**Comment by szepeviktor** [comment]
I'm sorry. Yes, it does.

![kép](https://user-images.githubusercontent.com/952007/151923221-4e10438c-6b79-4a01-b705-9f0fc67d9e0a.png)
