### ISSUE TITLE
Warn on duplicate headers with identical content

### ISSUE THREAD

**Issue by szepeviktor** [mnot/redbot#289]
E.g. [WP Engine](https://www.watobe.co.za/login/) has two `Vary: Accept-Encoding` headers. ([sometimes 3](https://redbot.org/?uri=https%3A%2F%2Fwpengine.com%2F))
Thank you for considering.

**Comment by mnot** [comment]
Yes - this is done for some headers, but a systematic approach would be better.

**Comment by mnot** [comment]
Dup :) of #115
