### ISSUE TITLE
"Error: Access Error" Check IP for Localhost

### ISSUE THREAD

**Issue by cdmastercom** [mnot/redbot#339]
The check IP function prevents testing or using redbot against local systems. So any usage like:

```bash
redbot http://127.0.0.1:3000
```
Root cause:
https://github.com/mnot/redbot/blob/6ac6c8ea7a1c1d890c56fc46988a55c09d7d2829/redbot/resource/fetch.py#L110-L121

When using redbot the error message is

```
Error: Access Error
```

Not sure if this is intended behaviour, but either way a better error message would be nice here. Using redbot on a local server is nice for development, so ideally users could disable this check somehow.

**Comment by mnot** [comment]
See `enable_local_access` in config.

**Comment by mholt** [comment]
Sorry for my naive question, but where does the config go? I found config.txt in the repo but I don't know how to actually use it. :thinking:

**Comment by mnot** [comment]
Its location is passed as an argument to `redbot_daemon`; e.g.,

> python bin/redbot_daemon config.txt

**Comment by mholt** [comment]
Thanks for replying! I'm actually using the CLI in my case (redbot, not redbot-daemon) and I guess I can't use a config file with it or access localhost. I'll see if
I can use the daemon then

**Comment by Anutrix** [comment]
Same issue. I am also using `redbot` cli.

Is there no way to use `redbot` cli with localhost?
Does cli support config yet?
