### ISSUE TITLE
Inet problem

### ISSUE THREAD

**Issue by bengyeng** [mnot/redbot#345]
![Screenshot_20231207_093901_Chrome](https://github.com/mnot/redbot/assets/133513298/e215efb7-5f86-4d68-9ca3-d2af5d2797b8)

problems, I just don't understand it

**Comment by bengyeng** [comment]
![Screenshot_20231207_095620_Chrome](https://github.com/mnot/redbot/assets/133513298/97beabf0-9255-4ad2-b2a9-308c69aba6fd)

**Comment by mnot** [comment]
Can you describe the problem you're seeing?

**Comment by bengyeng** [comment]
> Kunt u het probleem beschrijven dat u ondervindt?

extremely difficult to describe in such a concise manner.  Apparently I run via a server, but I have nothing to do with a company and just have a home network.  everything seems to be managed via an Apache server via Kubernetes.  Unfortunately, there is not enough knowledge to understand this properly, let alone explain and define it properly.

**Comment by mnot** [comment]
This project has nothing to do with that.

**Comment by bengyeng** [comment]
> Dit project heeft daar niets mee te maken.

Kunt u mij vertellen waar ik dan heen moet ?
